language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install --dev --prefer-source

before_commands:
  - "composer install --prefer-source"

before_install:
  - sudo add-apt-repository ppa:ultrafredde/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq task
  - task --version

script: ./vendor/bin/phpunit
